### PR TITLE
performance: compile regex only once

### LINKED ISSUE #795: 🐛 Bug Report: performance: regexes are compiled EACH time
## Describe the bug
We have some code that compiles a regex each time, resulting in high CPU usage (example: format_url, rewrite_urls functions in the utils.rs file)
We can see this when using getting a flamegraph

## Suggested fix

We should initialize them once with once_cell, so that we don't compile them each time as that is a significant waste of CPU cycles.

### PR DESCRIPTION
**Pull request by FireMasterK**
Closes #795

### CODE REVIEW

File: src/utils.rs [hunk 1]
```diff
@@ -777,6 +778,21 @@ pub async fn catch_random(sub: &str, additional: &str) -> Result<Response<Body>,
...
+static REGEX_FORMAT_5: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://v\.redd\.it/(.*)/DASH_([0-9]{2,4}(\.mp4|$|\?source=fallback))").unwrap());
+static REGEX_FORMAT_6: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://v\.redd\.it/(.+)/(HLSPlaylist\.m3u8.*)$").unwrap());
+static REGEX_FORMAT_7: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://i\.redd\.it/(.*)").unwrap());
+static REGEX_FORMAT_8: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://a\.thumbs\.redditmedia\.com/(.*)").unwrap());
+static REGEX_FORMAT_9: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://b\.thumbs\.redditmedia\.com/(.*)").unwrap());
+static REGEX_FORMAT_10: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://emoji\.redditmedia\.com/(.*)/(.*)").unwrap());
+static REGEX_FORMAT_11: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://preview\.redd\.it/(.*)").unwrap());
+static REGEX_FORMAT_12: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://external\-preview\.redd\.it/(.*)").unwrap());
+static REGEX_FORMAT_13: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://styles\.redditmedia\.com/(.*)").unwrap());
+static REGEX_FORMAT_14: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://www\.redditstatic\.com/(.*)").unwrap());
```
Comment (sigaloid) [inline src/utils.rs:794]: Perhaps these should have more significant names relating to their content.

**Review by sigaloid — COMMENTED** [review]
Thanks for the contribution! I'm going to leave this pending for now until i get a chance to look at the PR on a desktop, but it looks to go in, if nothing else is found. :)

**Review by sigaloid — COMMENTED** [review]
Looks great to me, thanks!
