### PR TITLE
Fix default subscriptions

### LINKED ISSUE #689: LIBREDDIT_DEFAULT_SUBSCRIPTIONS setting is no longer read
Since upgrading to v0.27.0, the $LIBREDDIT_DEFAULT_SUBSCRIPTIONS setting is not honoured as it was in previous versions. The result is that I see the a feed of random posts rather than the feeds that I am interested in. I think this was caused by the changes introduced by pull request #664.

Thanks
Keith

### PR DESCRIPTION
**Pull request by sigaloid**
Cut-down #706. Fixes #689

### CODE REVIEW

File: src/config.rs [hunk 1]
```diff
@@ -142,3 +147,8 @@ fn test_alt_env_config_precedence() {
 	write("libreddit.toml", config_to_write).unwrap();
 	assert_eq!(get_setting("LIBREDDIT_DEFAULT_COMMENT_SORT"), Some("top".into()))
 }
+#[test]
+#[sealed_test(env = [("LIBREDDIT_DEFAULT_SUBSCRIPTIONS", "news+bestof")])]
+fn test_default_subscriptions() {
+	assert_eq!(get_setting("LIBREDDIT_DEFAULT_SUBSCRIPTIONS"), Some("news+bestof".into()));
```
Comment (Daniel-Valentine) [inline src/config.rs:153]: This appears to contradict the format of environment variable as given in the README, so I would have expected `["news", "bestof"]`.

File: src/instance_info.rs [hunk 2]
```diff
@@ -153,10 +154,10 @@ impl InstanceInfo {
                 Deploy date: {}\n
                 Deploy timestamp: {}\n
                 Compile mode: {}\n
+				SFW only: {:?}\n
```
Comment (Daniel-Valentine) [inline src/instance_info.rs:157]: I agree we should move this around, but I think we should wait to do this in another deliverable.

File: src/main.rs [hunk 3]
```diff
@@ -161,7 +161,7 @@ async fn main() {
 	let mut app = server::Server::new();
 
 	// Force evaluation of statics. In instance_info case, we need to evaluate
-	// the timestamp so deploy date is accurate - in config case, we need to
```
Comment (Daniel-Valentine) [inline src/main.rs:164]: Surprised `rustfmt` didn't catch this.

**Review by Daniel-Valentine — CHANGES_REQUESTED** [review]

File: src/config.rs (hunk 1 above)
Comment (r7l) [reply src/config.rs:153]: Excuse me for jumping in here. But i've asked to create this PR as i really enjoyed this option so far and not having this option around leaves anyone using this option kinda stuck on 0.26.0. It was the last version with it.

Having it `linux+gnome+news` was [how it worked before](https://github.com/libreddit/libreddit/issues/560). 

Not saying it wouldn't work as you suggest but it feels kinda odd when Libreddit itself already [supports this syntax](https://libreddit.spike.codes/r/linux+gnome+news) and also Reddit works this way [as you can see here](https://www.reddit.com/r/linux+gnome+news).

Comment (Daniel-Valentine) [reply src/config.rs:153]: @r7l: I agree that we should reintroduce this feature, but we need to make sure that our documentation is consistent and correct.

Comment (r7l) [reply src/config.rs:153]: @Daniel-Valentine I might have misunderstood your comment. Sorry. Seems like it just needs a last fix to the README file instead of a rewrite to the subscription list. Good to hear.

File: src/instance_info.rs (hunk 2 above)
Comment (sigaloid) [reply src/instance_info.rs:157]: Ah, thanks. I should have only added the diffs that were relevant but I rather removed the diffs that looked irrelevant.

File: src/config.rs (hunk 1 above)
Comment (sigaloid) [reply src/config.rs:153]: :+1: Will fix the readme in the next commit.

File: README.md [hunk 4]
```diff
@@ -1,4 +1,4 @@
-# Libreddit
+
```
Comment (Daniel-Valentine) [inline README.md]: Oops. Let me fix this.

File: src/config.rs (hunk 1 above)
Comment (Daniel-Valentine) [reply src/config.rs:158]: @r7l:

> @Daniel-Valentine I might have misunderstood your comment. Sorry. Seems like it just needs a last fix to the README file instead of a rewrite to the subscription list. Good to hear.

Not an issue. Just wanted to make sure we're all on the same page.

**Comment by Daniel-Valentine** [comment]
@sigaloid: I went ahead and address the README changes. This is now good to go in.

**Review by Daniel-Valentine — APPROVED** [review]
